# Generated by Django 5.0.6 on 2024-06-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="users/user-default.jpg",
                null=True,
                upload_to="users/%Y/%m/%d/",
            ),
        ),
    ]
